<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Administration' => 'Ylläpito',
  'Are you sure you want to delete this item?' => 'Oletko varma että haluat poistaa tämän?',
  'CSV' => 'CSV',
  'Changes saved.' => 'Muutokset tallennettu.',
  'Changes saved. You can add a new entry.' => 'Muutokset tallennettu. Voit lisätä uuden.',
  'Choose {name}' => 'Valitse {name}',
  'Could not create folder "{dir}". Make sure "uploads" folder is writable.' => 'Kansiota "{dir}" ei voitu luoda. Varmista että "uploads"-kansiossa on kirjoitusoikeudet.',
  'Could not create upload folder "{dir}".' => '"uploads"-kansiota "{dir}" ei voitu luoda.',
  'Could not delete entry "{name}" with an ID "{pk}".' => 'Kohdetta "{name}" ei voitu poistaa ID:llä "{pk}".',
  'Could not load model "{name}".' => '"{name}" luokkaa ei voitu ladata.',
  'Could not save file or file exists: "{file}".' => 'Tiedostoa ei voitu tallentaa tai se on jo olemassa: "{file}".',
  'Could not upload file.' => 'Tiedostoa ei voitu tallentaa.',
  'Create' => 'Luo uusi',
  'Create {name}' => 'Luo uusi {name}',
  'Delete' => 'Poista',
  'Download' => 'Lataa',
  'Download {name}' => 'Lataa {name}',
  'Edit {name}' => 'Muokkaa {name}',
  'Error' => 'Virhe',
  'Excel' => 'Excel',
  'Home' => 'Koti',
  'Image' => 'Kuva',
  'Image preview' => 'Esikatselukuva',
  'Incorrect username or password.' => 'Virheellinen käyttäjätunnus tai salasana.',
  'Invalid file extension "{ext}".' => 'Virheellinen tiedostopääte "{ext}".',
  'List' => 'Listaa',
  'Login' => 'Kirjaudu sisään',
  'Logout' => 'Kirjaudu ulos',
  'MS CSV' => 'MS CSV',
  'Password' => 'Salasana',
  'Please configure "username" and "password" properties of the module in configuration file.' => 'Aseta moduulin "username" ja "password" -tietueet konfiguraatiotiedostoon.',
  'Please enter your username and password.' => 'Syötä käyttäjätunnus ja salasana.',
  'Preview' => 'Esikatselu',
  'Remember me next time' => 'Muista minut ensi kerralla',
  'Save' => 'Tallenna',
  'Save and add another' => 'Tallenna ja lisää uusi',
  'Save and continue editing' => 'Tallenna ja jatka muokkausta',
  'Username' => 'Käyttäjätunnus',
);
