<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
	'Add Tracking ID, Profile ID and Access Token to the main configuration file.' => 'Lisää Tracking ID, Profile ID ja Access Token main konfiguraatiotiedostoon.',
	'Administration' => 'Ylläpito',
	'Are you sure you want to delete this item?' => 'Haluatko varmasti poistaa tämän?',
	'Avg. Time on Page' => 'Keskim. sivulla käytetty aika',
	'Avg. Visit Duration' => 'Käynnin keskim. kesto',
	'Bounce Rate' => 'Poistumisprosentti',
	'CSV' => 'CSV',
	'Changes saved.' => 'Muutokset tallennettu.',
	'Changes saved. You can add a new entry.' => 'Muutokset tallennettu. Voit lisätä uuden.',
	'Choose {name}' => 'Valitse {name}',
	'Connect' => 'Yhdistä',
	'Connect with your Google Analytics account.' => 'Yhdistä Google Analytics -tililläsi.',
	'Could not create folder "{dir}". Make sure "uploads" folder is writable.' => 'Kansiota "{dir}" ei voitu luoda. Varmista että "uploads"-kansiossa on kirjoitusoikeudet.',
	'Could not create upload folder "{dir}".' => '"uploads"-kansiota "{dir}" ei voitu luoda.',
	'Could not delete entry "{name}" with an ID "{pk}".' => 'Kohdetta "{name}" ei voitu poistaa ID:llä "{pk}".',
	'Could not load model "{name}".' => '"{name}" luokkaa ei voitu ladata.',
	'Could not save file or file exists: "{file}".' => 'Tiedostoa ei voitu tallentaa tai se on jo olemassa: "{file}".',
	'Could not upload file.' => 'Tiedostoa ei voitu tallentaa.',
	'Create' => 'Luo uusi',
	'Create {name}' => 'Luo uusi {name}',
	'Delete' => 'Poista',
	'Desktop Pageviews' => 'Sivun katselut työpöydällä',
	'Device Traffic' => 'Liikenne laiteittain',
	'Direct {percentage}' => 'Suora {percentage}',
	'Download' => 'Lataa',
	'Download {name}' => 'Lataa {name}',
	'Edit {name}' => 'Muokkaa {name}',
	'Error' => 'Virhe',
	'Excel' => 'Excel',
	'Google Analytics setup' => 'Google Analytics -asennus',
	'Google Analytics summary for the past {days} days' => 'Google Analytics -yhteenveto viimeisen 30 päivän ajalta',
	'Home' => 'Koti',
	'Image' => 'Kuva',
	'Image preview' => 'Esikatselukuva',
	'Incorrect username or password.' => 'Virheellinen käyttäjätunnus tai salasana.',
	'Invalid file extension "{ext}".' => 'Virheellinen tiedostopääte "{ext}".',
	'Keyword' => 'Avainsana',
	'List' => 'Listaa',
	'Login' => 'Kirjaudu sisään',
	'Logout' => 'Kirjaudu ulos',
	'MS CSV' => 'MS CSV',
	'Metric' => 'Tieto',
	'New Visitors' => 'Uusia kävijöitä',
	'New Visits' => 'Uusia käyntejä',
	'Next' => 'Seuraava',
	'Overview' => 'Yleiskatsaus',
	'Page' => 'Sivu',
	'Pages / Visit' => 'Sivuja / käynti',
	'Pageviews' => 'Sivun katselut',
	'Password' => 'Salasana',
	'Paste authorization code here:' => 'Liitä auktorisointikoodi tähän:',
	'Please configure "username" and "password" properties of the module in configuration file.' => 'Aseta moduulin "username" ja "password" -tietueet konfiguraatiotiedostoon.',
	'Please enter your username and password.' => 'Syötä käyttäjätunnus ja salasana.',
	'Preview' => 'Esikatselu',
	'Referral {percentage}' => 'Viittaus {percentage}',
	'Referrer' => 'Viittaaja',
	'Reload page' => 'Lataa sivu uudelleen',
	'Remember me next time' => 'Muista minut ensi kerralla',
	'Save' => 'Tallenna',
	'Save and add another' => 'Tallenna ja lisää uusi',
	'Save and continue editing' => 'Tallenna ja jatka muokkausta',
	'Search {percentage}' => 'Haku {percentage}',
	'Select profile.' => 'Valitse profiili.',
	'Separate words with commas.' => 'Erottele sanat pilkulla.',
	'Smartphone Pageviews' => 'Sivun katselut älypuhelimella',
	'Statistics' => 'Tilastot',
	'Step {num}' => 'Vaihe {num}',
	'Tablet Pageviews' => 'Sivun katselut tabletilla',
	'There was an Google Analytics API service error {code}: {message}' => 'Google Analytics API -palvelussa sattui virhe {code}: {message}',
	'Top Keywords' => 'Yleisimmät hakusanat',
	'Top Pages' => 'Yleisimmät sivut',
	'Top Referrers' => 'Yleisimmät viittaajat',
	'Traffic Sources' => 'Liikenteen lähteet',
	'Unable to authenticate with Auth code {code}: {message}' => 'Ei voitu todentaa auktorisointikoodilla {code}: {message}',
	'Unique Pageviews' => 'Yksilöidyt sivun katselut',
	'Unique Visitors' => 'Yksilöidyt kävijät',
	'Username' => 'Käyttäjätunnus',
	'Value' => 'Arvo',
	'Visits' => 'Käynnit',
);