<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
	'Add Tracking ID, Profile ID and Access Token to the main configuration file.' => 'Добавить Tracking ID, Profile ID и Access Token в главный конфигурационный файл.',
	'Administration' => 'Администрирование',
	'Are you sure you want to delete this item?' => 'Вы уверены что хотите удалить этот элемент?',
	'Avg. Time on Page' => 'Средняя длительность пребывания на странице',
	'Avg. Visit Duration' => 'Средняя длительность посещения',
	'Bounce Rate' => 'Показатель отказов',
	'CSV' => 'CSV',
	'Changes saved.' => 'Изменения сохранены.',
	'Changes saved. You can add a new entry.' => 'Изменения сохранены, вы можете добавить новую запись.',
	'Choose {name}' => 'Выберите {name}',
	'Connect' => 'Подключиться',
	'Connect with your Google Analytics account.' => 'Подключить аккаунт Google Analytics.',
	'Could not create folder "{dir}". Make sure "uploads" folder is writable.' => 'Ошибка создания директории "{dir}". Убедитесь что директория "uploads" доступна для записи.',
	'Could not create upload folder "{dir}".' => 'Не могу создать директорию "{dir}".',
	'Could not delete entry "{name}" with an ID "{pk}".' => 'Ошибка удаления записи "{name}" с ID "{pk}".',
	'Could not load model "{name}".' => 'Ошибка загрузки модели "{name}".',
	'Could not save file or file exists: "{file}".' => 'Ошибка сохранения файла или файл уже существует: "{file}".',
	'Could not upload file.' => 'Ошибка загрузки файла.',
	'Create' => 'Добавить',
	'Create {name}' => 'Добавить {name}',
	'Delete' => 'Удалить',
	'Desktop Pageviews' => 'Desktop Pageviews',
	'Device Traffic' => 'Device Traffic',
	'Direct {percentage}' => 'Direct {percentage}',
	'Download' => 'Скачать',
	'Download {name}' => 'Скачать {name}',
	'Edit {name}' => 'Редактировать {name}',
	'Error' => 'Ошибка',
	'Excel' => 'Excel',
	'Google Analytics setup' => 'Настройки Google Analytics',
	'Google Analytics summary for the past {days} days' => 'Суммарная статистика Google Analytics за {days} дней',
	'Home' => 'Контент',
	'Image' => 'Изображение',
	'Image preview' => 'Предпросмотр',
	'Incorrect username or password.' => 'Неверное имя пользователя или пароль.',
	'Invalid file extension "{ext}".' => 'Неверное расширение файла "{ext}".',
	'Keyword' => 'Ключевые слова',
	'List' => 'Список',
	'Login' => 'Войти',
	'Logout' => 'Выйти',
	'MS CSV' => 'MS CSV',
	'Metric' => 'Метрика',
	'New Visitors' => 'Новые посетители',
	'New Visits' => 'Новые посещения',
	'Next' => 'Далее',
	'Overview' => 'Описание',
	'Page' => 'Страница',
	'Pages / Visit' => 'Страницы / Посещений',
	'Pageviews' => 'Просмотры страницы',
	'Password' => 'Пароль',
	'Paste authorization code here:' => 'Вставьте код авторизации здесь:',
	'Please configure "username" and "password" properties of the module in configuration file.' => 'Заполните свойства "username" и "password" в настройках модуля.',
	'Please enter your username and password.' => 'Введите ваш логин и пароль.',
	'Preview' => 'Предпросмотр',
	'Ссылки {percentage}' => 'Viittaus {percentage}',
	'Referrer' => 'Referrer',
	'Reload page' => 'Перезагрузить страницу',
	'Remember me next time' => 'Запомнить меня',
	'Save' => 'Сохранить',
	'Save and add another' => 'Сохранить и добавить',
	'Save and continue editing' => 'Применить',
	'Search {percentage}' => 'Поиск {percentage}',
	'Select profile.' => 'Выберите профиль.',
	'Separate words with commas.' => 'Разделяйте слова запятыми.',
	'Smartphone Pageviews' => 'Просмотрено со смартфонов',
	'Statistics' => 'Статистика',
	'Step {num}' => 'Шаг {num}',
	'Tablet Pageviews' => 'Просмотрено с плашнетов',
	'There was an Google Analytics API service error {code}: {message}' => 'Ошибка Google Analytics API {code}: {message}',
	'Top Keywords' => 'Топ ключевых слов',
	'Top Pages' => 'Топ страниц',
	'Top Referrers' => 'Топ ссылающихся',
	'Traffic Sources' => 'Источник трафика',
	'Unable to authenticate with Auth code {code}: {message}' => 'Ошибка аутентификации с кодом {code}: {message}',
	'Unique Pageviews' => 'Уникальных просмотров',
	'Unique Visitors' => 'Уникальных посетителей',
	'Username' => 'Имя Пользователя',
	'Value' => 'Значение',
	'Visits' => 'Посещений',
    'Before add images to product gallery, you need to save item' => 'Прежде чем добавить изображения вам необходимо создать элемент',
    'Tree' => 'Дерево',
    'View on site' => 'Смотреть на сайте',
    'Page hidden, view on site unable' => 'Страница скрыта, просмотр на сайте новозможен',
    'Show tree' => 'Развернуть',
    'Hide tree' => 'Свернуть',
    'Switch tree' => 'Переключить',
    'Elements' => 'Элементы',
    'Set sort' => 'Задать сортировку',
    'Enter sort value' => 'Введите значение сортировки',
    'Pages' => 'Страницы',
    "Permissions error, you don't have right for run this operation" => 'Ошибка прав доступа, у вас нет прав на выполнение данной операции'
);