<?php
/**
* Message translations.
*
* This file is automatically generated by 'yiic message' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE, this file must be saved in UTF-8 encoding.
*
* @version $Id: $
*/
return array (
	'Administration' => 'Панель администрирования',
	'Add Tracking ID, Profile ID and Access Token to the main configuration file.' => 'Настройте Tracking ID, Profile ID и Access Token в файле конфигурации приложения.',
	'Are you sure you want to delete this item?' => 'Уверены, что хотите удалить?',
	'Avg. Time on Page' => 'Средняя длительность просмотра страницы',
	'Avg. Visit Duration' => 'Средняя длительность посещения',
	'Bounce Rate' => 'Показатель отказов',
	'Changes saved.' => 'Изменения сохранены.',
	'Changes saved. You can add a new entry.' => 'Изменения сохранены. Вы можете добавить новую запись.',
	'Choose {name}' => 'Выберите {name}',
	'Connect' => 'Подключить',
	'Connect with your Google Analytics account.' => 'Подключить аккаунт Google Analytics.',
	'Could not create folder "{dir}". Make sure "uploads" folder is writable.' => 'Не удалось создать каталог "{dir}". Убедитесь, что каталог "uploads" доступен для записи.',
	'Could not create upload folder "{dir}".' => 'Не удалось создать каталог для заливки "{dir}".',
	'Could not delete entry "{name}" with an ID "{pk}".' => 'Не удалось удалить модель "{name}" с ключом "{pk}".',
	'Could not load model "{name}".' => 'Не удалось загрузить модель "{name}".',
	'Could not save file or file exists: "{file}".' => 'Файл "{file}" существует, либо не может быть создан.',
	'Could not upload file.' => 'Не удалось загрузить файл.',
	'Create' => 'Создать',
	'Create {name}' => 'Создать {name}',
	'Delete' => 'Удалить',
	'Desktop Pageviews' => 'Просмотры с компьютера',
	'Device Traffic' => 'Трафик с устройств',
	'Direct {percentage}' => 'Direct {percentage}',
	'Download' => 'Скачать',
	'Download {name}' => 'Скачать {name}',
	'Edit {name}' => 'Редактирование {name}',
	'Error' => 'Ошибка',
	'Google Analytics setup' => 'Настройка Google Analytics',
	'Google Analytics summary for the past {days} days' => 'Google Analytics отчет за последние {days} дней',
	'Home' => 'На главную',
	'Image' => 'Изображение',
	'Image preview' => 'Просмотр изображения',
	'Incorrect username or password.' => 'Неправильное имя пользователя или пароль.',
	'Invalid file extension "{ext}".' => 'Неправильное расширение файла "{ext}".',
	'Keyword' => 'Ключевое слово',
	'List' => 'Список',
	'Login' => 'Вход',
	'Logout' => 'Выход',
	'Metric' => 'Метрика',
	'New Visitors' => 'Новые посетители',
	'New Visits' => 'Новые посещения',
	'Next' => 'Следующий',
	'Overview' => 'Обзор',
	'Page' => 'Страница',
	'Pages / Visit' => 'Страницы / Посещения',
	'Pageviews' => 'Просмотры страниц',
	'Password' => 'Пароль',
	'Paste authorization code here:' => 'Вставьте код авторизации:',
	'Please configure "username" and "password" properties of the module in configuration file.' => 'Установите параметры "username" and "password" в конфигурации подключения модуля.',
	'Please enter your username and password.' => 'Введите свои логин и пароль.',
	'Preview' => 'Превью',
	'Referral {percentage}' => 'Referral {percentage}',
	'Referrer' => 'Referrer',
	'Reload page' => 'Перезагрузить страницу',
	'Remember me next time' => 'Запомнить',
	'Save' => 'Сохранить',
	'Save and add another' => 'Сохранить и создать еще',
	'Save and continue editing' => 'Сохранить и продолжить редактирование',
	'Search {percentage}' => 'Поисковой {percentage}',
	'Select profile.' => 'Выбор профиля.',
	'Separate words with commas.' => 'Отдельные слова.',
	'Smartphone Pageviews' => 'Просмотры через смартфон',
	'Statistics' => 'Статистика',
	'Step {num}' => 'Шаг {num}',
	'Tablet Pageviews' => 'Просмотры через планшет',
	'There was an Google Analytics API service error {code}: {message}' => 'Произошла ошибка в Google Analytics API {code}: {message}',
	'Top Keywords' => 'Популярные ключевые слова',
	'Top Pages' => 'Популярные страницы',
	'Top Referrers' => 'Популярные источники',
	'Traffic Sources' => 'Источники трафика',
	'Unable to authenticate with Auth code {code}: {message}' => 'Ошибка при аутентификации {code} : {message}',
	'Unique Pageviews' => 'Уникальные просмотры',
	'Unique Visitors' => 'Уникальные посетители',
	'Username' => 'Имя пользователя',
	'Value' => 'Значение',
	'Visits' => 'Посещения',
);
