<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
	'Administration' => '管理后台',
	'Are you sure you want to delete this item?' => '确定要删除它？',
	'CSV' => 'CSV',
	'Changes saved.' => '已保存',
	'Save failed.' => '保存失败',
	'Changes saved. You can add a new entry.' => '已保存，继续添加。',
	'Choose {name}' => '请选择 {name}',
	'Could not create folder "{dir}". Make sure "uploads" folder is writable.' => '不能创建 "{dir}" "uploads"文件夹不可写？',
	'Could not create upload folder "{dir}".' => '不能创建上传文件夹 "{dir}"',
	'Could not delete entry "{name}" with an ID "{pk}".' => '不能删除ID为 {pk} 的 "{name}"',
	'Could not load model "{name}".' => '不能加载模型"{name}"',
	'Could not save file or file exists: "{file}".' => '不能保存文件 {file}或已存在同名文件：',
	'Could not upload file.' => '不能上传文件',
	'Create' => '创建',
	'Create {name}' => '创建{name}',
	'Delete' => '删除',
	'Download' => '下载',
	'Download {name}' => '下载 {name}',
	'Edit {name}' => '编辑 {name}',
	'Error' => '错误',
	'Excel' => 'Excel',
	'Home' => '主页',
	'Image' => '图片',
	'Image preview' => '图片预览',
	'Incorrect username or password.' => '用户名或密码不对',
	'Invalid file extension "{ext}".' => '无效的文件扩展名 "{ext}"',
	'List' => '所有内容', //感觉“列表”不太好
	'Login' => '登陆',
	'Logout' => '注销',
	'MS CSV' => 'MS CSV',
	'Password' => '密码',
	'Please configure "username" and "password" properties of the module in configuration file.' => '请先去配置文件里面修改"username"和"password"',
	'Please enter your username and password.' => '请填写用户名和密码',
	'Preview' => '预览',
	'Remember me next time' => '下次记住我',
	'Save' => '保存',
	'Save and add another' => '保存并继续添加',
	'Save and continue editing' => '保存并继续编辑',
	'Username' => '用户名',
);
