<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
	'Add Tracking ID, Profile ID and Access Token to the main configuration file.' => '请先在主配置文件中添加Tracking ID,Profile ID和Access Token',
	'Administration' => '后台管理',
	'Are you sure you want to delete this item?' => '你确定要删除这个项目?',
	'Avg. Time on Page' => '平均页面停留时间',
	'Avg. Visit Duration' => '平均访问持续时间',
	'Bounce Rate' => '跳出率',
	'CSV' => 'CSV',
	'Changes saved.' => '更改已保存',
	'Changes saved. You can add a new entry.' => '更改已保存,你可以继续添加.',
	'Choose {name}' => '选择 {name}',
	'Connect' => '连接',
	'Connect with your Google Analytics account.' => '使用你的Google分析账户连接',
	'Could not create folder "{dir}". Make sure "uploads" folder is writable.' => '无法创建文件夹"{dir}",请确保"uploads"文件夹可写.',
	'Could not create upload folder "{dir}".' => '无法创建上传文件夹"{dir}"',
	'Could not delete entry "{name}" with an ID "{pk}".' => '无法删除ID为"{pk}"的记录"{name}".',
	'Could not load model "{name}".' => '无法加载模型"{name}"',
	'Could not save file or file exists: "{file}".' => '无法保存文件"{file}",可能文件已存在.',
	'Could not upload file.' => '无法上传文件',
	'Create' => '创建',
	'Create {name}' => '创建{name}',
	'Delete' => '删除',
	'Desktop Pageviews' => 'PC访问量',
	'Device Traffic' => '移动设备流量',
	'Direct {percentage}' => '直接来访{percentage}',
	'Download' => '下载',
	'Download {name}' => '下载{name}',
	'Edit {name}' => '编辑{name}',
	'Error' => '错误',
	'Excel' => 'Excel',
	'Google Analytics setup' => 'Google分析设置',
	'Google Analytics summary for the past {days} days' => '最近30天的Google分析概况',
	'Home' => '主页',
	'Image' => '图片',
	'Image preview' => '图片预览',
	'Incorrect username or password.' => '错误的用户名或密码',
	'Invalid file extension "{ext}".' => '非法的文件扩展名"{ext}".',
	'Keyword' => '关键词',
	'List' => '内容列表',
	'Login' => '登陆',
	'Logout' => '注销',
	'MS CSV' => 'MS CSV',
	'Metric' => '指标',
	'New Visitors' => '新访客人数',
	'New Visits' => '新访问次数',
	'Next' => '下一个',
	'Overview' => '概览',
	'Page' => '页面',
	'Pages / Visit' => '每次访问的网页浏览量',
	'Pageviews' => '浏览量',
	'Password' => '密码',
	'Paste authorization code here:' => '将授权代码粘贴到这里:',
	'Please configure "username" and "password" properties of the module in configuration file.' => '请更改配置文件中本模块的username和password属性',
	'Please enter your username and password.' => '请输入用户名和密码',
	'Preview' => '预览',
	'Referral {percentage}' => '引荐流量 {percentage}',
	'Referrer' => '引荐',
	'Reload page' => '刷新页面',
	'Remember me next time' => '下次记住我',
	'Save' => '保存',
	'Save and add another' => '保存并继续添加',
	'Save and continue editing' => '保存并继续编辑',
	'Search {percentage}' => '搜索 {percentage}',
	'Select profile.' => '选择配置文件',
	'Smartphone Pageviews' => '智能手机浏览量',
	'Statistics' => '统计',
	'Step {num}' => '步骤 {num}',
	'Tablet Pageviews' => '平板电脑浏览量',
	'There was an Google Analytics API service error {code}: {message}' => 'Google分析API服务错误{code}: {message}',
	'Top Keywords' => '关键词',
	'Top Pages' => '目标页面',
	'Top Referrers' => '来源',
	'Traffic Sources' => '流量来源',
	'Unable to authenticate with Auth code {code}: {message}' => '无法通过授权代码获得授权{code}: {message}',
	'Unique Pageviews' => '唯一身份浏览量',
	'Unique Visitors' => '唯一访客',
	'Username' => '用户名',
	'Value' => '值',
	'Visits' => '访问量',
);
