<?php
/**
* Message translations.
*
* This file is automatically generated by 'yiic message' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE, this file must be saved in UTF-8 encoding.
*
* @version $Id: $
*/
return array (
	'Add Tracking ID, Profile ID and Access Token to the main configuration file.' => 'Füge "Tracking ID", "Profile ID" und "Access Token" zur Hauptkonfigurationsdatei hinzu.',
	'Are you sure you want to delete this item?' => 'Bist du sicher, dass du dieses Objekt löschen möchtest?',
	'Avg. Time on Page' => 'Durchschnittliche Zeit auf der Seite',
	'Avg. Visit Duration' => 'Durchschnittliche Aufenthaltszeit',
	'Bounce Rate' => 'Absprungrate',
	'Changes saved.' => 'Änderungen gespeichert.',
	'Changes saved. You can add a new entry.' => 'Änderungen gespeichert. Du kannst einen neuen Eintrag hinzufügen.',
	'Choose {name}' => '{name} auswählen',
	'Connect' => 'Verbinden',
	'Connect with your Google Analytics account.' => 'Verbinde dich mit deinem Google Analytics Account.',
	'Could not create folder "{dir}". Make sure "uploads" folder is writable.' => 'Das Verzeichnis "{dir}" konnte nicht erstellt werden. Vergewissere dich , dass das "uploads"-Verzeichnis schreibbar ist.',
	'Could not create upload folder "{dir}".' => '"Das "uploads"-Verzeichnis "{dir}" konnte nicht erstellt werden.',
	'Could not delete entry "{name}" with an ID "{pk}".' => 'Der Eintrag "{name}" mit der ID "{pk}" konnte nicht erstellt werden.',
	'Could not load model "{name}".' => 'Das Modul "{name}" konnte nicht geladen werden.',
	'Could not save file or file exists: "{file}".' => 'Die Datei konnte nicht gespeichert werden oder existiert schon: "{file}".',
	'Could not upload file.' => 'Die Datei konnte nicht hochgeladen werden.',
	'Create' => 'Hinzufügen',
	'Create {name}' => '{name} hinzufügen',
	'Delete' => 'Löschen',
	'Desktop Pageviews' => 'Aufrufe vom Desktop',
	'Device Traffic' => 'Verbrauch pro Gerät',
	'Direct {percentage}' => 'Direkter Seitenaufruf {percentage}',
	'Download' => 'Herunterladen',
	'Download {name}' => '{name} herunterladen',
	'Edit {name}' => '{name} bearbeiten',
	'Error' => 'Fehler',
	'Google Analytics setup' => 'Google Analytics Einstellungen',
	'Google Analytics summary for the past {days} days' => 'Google Analytics Zusammenfassung für die letzten {days} Tage',
	'Home' => 'Start',
	'Image' => 'Bild',
	'Image preview' => 'Bildvorschau',
	'Incorrect username or password.' => 'Falscher Benutzername oder falsches Passwort.',
	'Invalid file extension "{ext}".' => 'Ungültige Dateiendung "{ext}".',
	'Keyword' => 'Schlüsselwort',
	'List' => 'Auflisten',
	'Login' => 'Anmelden',
	'Logout' => 'Abmelden',
	'Metric' => 'Metrik',
	'New Visitors' => 'Neue Besucher',
	'New Visits' => 'Neue Besuche',
	'Next' => 'Weiter',
	'Overview' => 'Übersicht',
	'Page' => 'Seite',
	'Pages / Visit' => 'Seiten / Besuch',
	'Pageviews' => 'Seitenaufrufe',
	'Password' => 'Passwort',
	'Paste authorization code here:' => 'Authorisierungscode hier einfügen:',
	'Please configure "username" and "password" properties of the module in configuration file.' => 'Bitte konfiguriere "username" und "password" Einstellungen der Moduls in der Konfigurationsdatei.',
	'Please enter your username and password.' => 'Bitte Benutzername und Passwort eingeben.',
	'Preview' => 'Vorschau',
	'Referral {percentage}' => 'Via Verweis {percentage}',
	'Referrer' => 'Verweis',
	'Reload page' => 'Seite neuladen',
	'Remember me next time' => 'Zugang merken',
	'Save' => 'Speichern',
	'Save and add another' => 'Speichern und noch einen Eintrag hinzufügen',
	'Save and continue editing' => 'Speichern und weiter bearbeiten',
	'Search {percentage}' => 'Via Suche {percentage}',
	'Select profile.' => 'Profil wählen.',
	'Separate words with commas.' => 'Einzelne Worte mit Komma getrennt.',
	'Smartphone Pageviews' => 'Seitenaufrufe über mobile Geräte',
	'Statistics' => 'Statistiken',
	'Step {num}' => 'Schritt {num}',
	'Tablet Pageviews' => 'Seitenaufrufe über Tablets',
	'There was an Google Analytics API service error {code}: {message}' => 'Ein Google Analytics API Fehler ist aufgetreten {code}: {message}',
	'Top Keywords' => 'Häufigste Schlüsselworte',
	'Top Pages' => 'Häufigste Seiten',
	'Top Referrers' => 'Häufigste Verweise',
	'Traffic Sources' => 'Verkehrsquelle',
	'Unable to authenticate with Auth code {code}: {message}' => 'Authentisierung mit dem Auth-Code {code} nicht möglich: {message}',
	'Unique Pageviews' => 'Eideutige Seitenaufrufe',
	'Unique Visitors' => 'Eindeutige Besucher',
	'Username' => 'Benutzername',
	'Value' => 'Wert',
	'Visits' => 'Besuche',
);
